version: '3.3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: library
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: sh -c 'echo "[client]\nuser=root\npassword=$${MARIADB_ROOT_PASSWORD:-toor}" > /root/.my.cnf && docker-entrypoint.sh mysqld &&
                    echo "CREATE DATABASE IF NOT EXISTS library;" > /docker-entrypoint-initdb.d/create_library_db.sql &&
                    docker-entrypoint.sh mysqld --sql_mode="STRICT_TRANS_TABLES,ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'
    ports:
      - 3306:3306

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - ./:/minio/data

  app:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${APP_PORT}:3000
    command: sh -c "yarn && yarn build && yarn start:dev"
    depends_on:
      - db
